#!/bin/bash
## bash < <(curl -s https://raw.githubusercontent.com/JosiahKerley/virt-maker/master/install-online)

## Prereqs
cwd=`pwd`
pkg=None
if which yum; then pkg=yum; fi
if which apt-get; then pkg=apt-get; fi
if [ "$pkg" == "None" ]; then echo "Unknown Package Manager"; exit 1; fi
if ! which git; then $pkg install -y git; fi


## Fetch
cd /tmp
rm -rf virt-maker
if ! git clone https://github.com/JosiahKerley/virt-maker; then echo "Clone failed"; exit 1; fi
cd virt-maker


## Install
bash install-safe
if [ ! -f /usr/local/bin/virt-maker ]; then echo "It doesn't look like it installed"; exit 1


## Other
yum install -y libguestfs* virt-* || apt-get install -y libguestfs* virt-*


## Cleanup
cd "$cwd"
rm -rf /tmp/virt-maker
exit 0
