#!/bin/bash
BIN_PREFIX='/usr/local/bin'
LIB_PREFIX='/var/lib/virt-maker'
PYTHON_PREFIX='/usr/lib/python2.7/site-packages'
PACKER_FILE='packer_0.8.6_linux_amd64.zip'


function main() {
  cleanup;
  pythonDeps;
  pkgSetup;
  packerSetup;
}

function pkgSetup() {
  cat virt-maker/__init__.py > ${BIN_PREFIX}/virt-maker;
  chmod 1750 ${BIN_PREFIX}/virt-maker;
  chown root:libvirt ${BIN_PREFIX}/virt-maker;

  mkdir -p ${LIB_PREFIX};
  chmod 2770 ${LIB_PREFIX};
  mkdir -m 2770 -p ${LIB_PREFIX}/{cache,providers};
  yes | cp -r providers/* ${LIB_PREFIX}/providers/;
  chown -R root:libvirt ${LIB_PREFIX};
}

function packerSetup() {
  if ! which packer
  then
    APP=packer
    TEMP=$(mktemp -p /tmp -d ${APP}-XXXX);
    cd ${TEMP};
    wget "https://dl.bintray.com/mitchellh/packer/${PACKER_FILE}"
    unzip ${PACKER_FILE};
    rm -f ${PACKER_FILE};
    sudo cp -f packer* ${BIN_PREFIX};
    rm -rf ${TEMP};
  fi;
}

function pythonDeps() {
  if ! which redis-cli; then yum install -y redis; fi;
  if ! which pip; then yum install -y python-pip; fi;
  if ! ls ${PYTHON_PREFIX}/filelock; then pip install filelock; fi;
  if ! ls ${PYTHON_PREFIX}/jinja2; then pip install jinja2; fi;
  if ! ls ${PYTHON_PREFIX}/redis; then pip install redis; fi;
  if ! ls ${PYTHON_PREFIX}/pexpect; then pip install pexpect; fi;
  if ! ls ${PYTHON_PREFIX}/flask; then pip install flask; fi;
}

function cleanup() {
  rm -rf ${LIB_PREFIX};
  rm -rf ${BIN_PREFIX}/virt-maker;
  rm -rf ${BIN_PREFIX}/packer*;
  # just for gigs... remove jo's native "/usr/bin" stuffs <- bad Jo... <- Retort: find /usr/bin | grep "/virt[-]" :p
  rm -rf /usr/bin/virt-maker;
}

main "$@";
